name: solar_cargo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  provider: ^6.1.1
  image_picker: ^0.8.7+4
  http: ^0.13.5
  path_provider: ^2.0.12
  mobile_scanner: ^3.0.0
  flutter_tesseract_ocr: ^0.4.28
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/tessdata_config.json
    - assets/tessdata/eng.traineddata
    - assets/tessdata/bul.traineddata
flutter_intl:
  enabled: true
