name: solar_cargo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  provider: ^6.1.1
  image_picker: ^0.8.7+4
  http: ^1.1.0
  path_provider: ^2.0.12
  logger: ^2.5.0
  hexcolor: ^3.0.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: 2.0.10+1
  flash: 3.1.0
  lottie: ^3.1.2
  jwt_decoder: ^2.0.1
  dio: ^5.2.1
  easy_debounce: 2.0.3
  flutter_typeahead: 4.8.0
  permission_handler: ^10.4.0
  file_picker: ^6.1.1
  open_file: ^3.3.2
  dropdown_button2: ^2.3.9
  image_gallery_saver_plus: ^4.0.1
  flutter_exif_rotation: ^0.5.2

dependency_overrides:
  flutter_keyboard_visibility:
    path: overrides/flutter_keyboard_visibility
  image_gallery_saver:
    path: overrides/image_gallery_saver
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/miscellaneous/
    - assets/lottie/
    - assets/icons/home_screen/
flutter_intl:
  enabled: true
